/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Weather: typeof import('./src/components/Weather.vue')['default']
    WeatherDashboard: typeof import('./src/components/WeatherDashboard.vue')['default']
    WeatherDataCard: typeof import('./src/components/WeatherDataCard.vue')['default']
    WeatherDescription: typeof import('./src/components/WeatherDescription.vue')['default']
    WeatherDisplay: typeof import('./src/components/WeatherDisplay.vue')['default']
    WeatherForm: typeof import('./src/components/WeatherForm.vue')['default']
    WeatherInfo: typeof import('./src/components/WeatherInfo.vue')['default']
    WeatherMap: typeof import('./src/components/WeatherMap.vue')['default']
  }
}
